-- MySQL Script generated by MySQL Workbench
-- Wed Mar  3 15:32:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema flowerpower
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `flowerpower` ;

-- -----------------------------------------------------
-- Schema flowerpower
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flowerpower` DEFAULT CHARACTER SET utf8 ;
USE `flowerpower` ;

-- -----------------------------------------------------
-- Table `flowerpower`.`winkel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowerpower`.`winkel` ;

CREATE TABLE IF NOT EXISTS `flowerpower`.`winkel` (
  `idwinkel` INT NOT NULL AUTO_INCREMENT,
  `winkeladres` VARCHAR(245) NOT NULL,
  `winkelpostcode` VARCHAR(6) NOT NULL,
  `winkelplaats` VARCHAR(45) NOT NULL,
  `winkeltelefoon` VARCHAR(10) NOT NULL,
  `winkelemail` VARCHAR(245) NOT NULL,
  PRIMARY KEY (`idwinkel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flowerpower`.`klant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowerpower`.`klant` ;

CREATE TABLE IF NOT EXISTS `flowerpower`.`klant` (
  `idklant` INT NOT NULL AUTO_INCREMENT,
  `klantvoornaam` VARCHAR(45) NOT NULL,
  `klanttussenvoegsel` VARCHAR(45) NULL,
  `klantachternaam` VARCHAR(45) NOT NULL,
  `klantadres` VARCHAR(245) NOT NULL,
  `klanthuisnummer` VARCHAR(10) NOT NULL,
  `klantpostcode` VARCHAR(6) NOT NULL,
  `klantplaats` VARCHAR(45) NOT NULL,
  `klanttelefoon` VARCHAR(10) NOT NULL,
  `klantemail` VARCHAR(245) NOT NULL,
  `klantpassword` VARCHAR(245) NOT NULL,
  PRIMARY KEY (`idklant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flowerpower`.`medewerker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowerpower`.`medewerker` ;

CREATE TABLE IF NOT EXISTS `flowerpower`.`medewerker` (
  `idmedewerker` INT NOT NULL,
  `medewerkervoornaam` VARCHAR(45) NOT NULL,
  `medewerkertussenvoegsel` VARCHAR(45) NULL,
  `medewerkerachternaam` VARCHAR(45) NOT NULL,
  `medewerkeradres` VARCHAR(245) NOT NULL,
  `medewerkerhuisnummer` VARCHAR(10) NOT NULL,
  `medewerkerpostcode` VARCHAR(6) NOT NULL,
  `medewerkerplaats` VARCHAR(45) NOT NULL,
  `medewerkertelefoon` VARCHAR(10) NOT NULL,
  `medewerkeremail` VARCHAR(245) NOT NULL,
  `medewerkerpassword` VARCHAR(245) NOT NULL,
  PRIMARY KEY (`idmedewerker`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flowerpower`.`artikel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowerpower`.`artikel` ;

CREATE TABLE IF NOT EXISTS `flowerpower`.`artikel` (
  `idartikel` INT NOT NULL,
  `omschrijving` VARCHAR(245) NOT NULL,
  `prijs` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idartikel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flowerpower`.`factuur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowerpower`.`factuur` ;

CREATE TABLE IF NOT EXISTS `flowerpower`.`factuur` (
  `idfactuur` INT NOT NULL,
  `idklant` INT NOT NULL,
  `idmedewerker` INT NULL,
  `idwinkel` INT NOT NULL,
  `datum` DATE NOT NULL,
  `afgehaald` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idfactuur`),
  INDEX `fk_factuur_klant_idx` (`idklant` ASC) VISIBLE,
  INDEX `fk_factuur_medewerker1_idx` (`idmedewerker` ASC) VISIBLE,
  INDEX `fk_factuur_winkel1_idx` (`idwinkel` ASC) VISIBLE,
  CONSTRAINT `fk_factuur_klant`
    FOREIGN KEY (`idklant`)
    REFERENCES `flowerpower`.`klant` (`idklant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factuur_medewerker1`
    FOREIGN KEY (`idmedewerker`)
    REFERENCES `flowerpower`.`medewerker` (`idmedewerker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factuur_winkel1`
    FOREIGN KEY (`idwinkel`)
    REFERENCES `flowerpower`.`winkel` (`idwinkel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flowerpower`.`artikel_has_factuur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowerpower`.`artikel_has_factuur` ;

CREATE TABLE IF NOT EXISTS `flowerpower`.`artikel_has_factuur` (
  `artikel_idartikel` INT NOT NULL,
  `factuur_idfactuur` INT NOT NULL,
  `aantal` INT NULL,
  PRIMARY KEY (`artikel_idartikel`, `factuur_idfactuur`),
  INDEX `fk_artikel_has_factuur_factuur1_idx` (`factuur_idfactuur` ASC) VISIBLE,
  INDEX `fk_artikel_has_factuur_artikel1_idx` (`artikel_idartikel` ASC) VISIBLE,
  CONSTRAINT `fk_artikel_has_factuur_artikel1`
    FOREIGN KEY (`artikel_idartikel`)
    REFERENCES `flowerpower`.`artikel` (`idartikel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artikel_has_factuur_factuur1`
    FOREIGN KEY (`factuur_idfactuur`)
    REFERENCES `flowerpower`.`factuur` (`idfactuur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
